[package]
name = "proper-evm-sniper"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.2.1", features = ["full"] }
dotenv = "0.15.0"
tokio = { version = "1.10.0", features = ["full"] }
tokio-postgres = "0.7.11"
futures-util = "0.3.30"
